train:
  lr: 0.001
  momentum: 0.9
  epochs: 1

model:
  _target_: torchvision.models.detection.fasterrcnn_resnet50_fpn
  pretrained: True

optimizers:
  _target_: torch.optim.SGD
  params:
    lr: ${models.params.train.lr}
    momentum: ${models.params.train.momentum}

classifier:
  _target_: torchvision.models.detection.faster_rcnn.FastRCNNPredictor
  in_channels: 1024
  num_classes: ${models.params.num_classes}

num_classes: 5
frozen_layers: 999
trainable_layers:
  - layer4