data:
  train: 'model/data/leaves'

training: 'lightning'
workers: 12
defaults:
  - models: resnet
  - override hydra/launcher: basic
  - override hydra/sweeper: basic
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      models: resnet
      models/params: resnet/params2